### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Prinzhorn** [malwareinfosec/fiddleitm#1]
1. `flow.response.content.decode('utf-8', 'ignore')` -> `flow.response.text` (it has heuristics to guess the correct encoding)
2. `flow.request.path` -> `flow.request.url/pretty_url` (at least it looks like the regex is supposed to match the full URL?)
3. Look into [addon classes](https://docs.mitmproxy.org/stable/addons-overview/) and move the init/fetching logic to `__init__` or [`load`](https://docs.mitmproxy.org/stable/api/events.html#LifecycleEvents.load)

**Comment by malwareinfosec** [comment]
Thanks for the feedback! I have implemented those changes, hopefully correctly.
